[package]
name = "sila-transpiler-infrastructure"
version = "0.3.4"
edition = "2021"
license = "MIT"
authors = ["梶塚太智 <kajizukataichi@outlook.jp>"]
description = "The simple transpiler infrastructure for every platform"
repository = "https://github.com/KajizukaTaichi/sila"

[dependencies]
