[package]
name = "sila"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["梶塚太智 <kajizukataichi@outlook.jp>"]
description = "The simple transpiler infrastructure for every platform"

[dependencies]
